version: '3.9'

services:

  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD_FILE: /run/secrets/sql_password
      MSSQL_BACKUP_DIR: /var/opt/mssql/bak/
      MSSQL_COLLATION: Cyrillic_General_CI_AS
    ports:
      - '192.168.236.101:1433:1433/tcp'
    volumes:
      - 'sql:/var/opt/mssql'
    secrets:
      - sql_password

volumes:
  sql:

secrets:
  sql_password:
    file: ./secrets/sql_password.txt
