execute pathogen#infect()

" Switch syntax highlighting on, when the terminal has colors
syntax on
filetype plugin indent on

" No backup files
set nobackup

" No write backup
set nowritebackup

" No swap file
set noswapfile

" Command history
set history=100

" Always show cursor
set ruler

" Show incomplete commands
set showcmd

" Incremental searching (search as you type)
set incsearch

" Highlight search matches
set hlsearch

" Ignore case in search
set smartcase

" Make sure any searches /searchPhrase doesn't need the \c escape character
set ignorecase

" Turn word wrap off
set nowrap

" Allow backspace to delete end of line, indent and start of line characters
set backspace=indent,eol,start

" Convert tabs to spaces
set expandtab

" Set tab size in spaces (this is for manual indenting)
set tabstop=4

" The number of spaces inserted for a tab (used for auto indenting)
set shiftwidth=4

" Turn on line numbers
set number

" Always show status bar
set laststatus=2

" Set the status line to something useful
set statusline=%f\ %=L:%l/%L\ %c\ (%p%%)

" UTF encoding
set encoding=utf-8

" Don't show intro
set shortmess+=I

" Always highlight column 100 so it's easier to see where
" cutoff appears on longer screens
set colorcolumn=100

" Set hide buffer
set hidden

" The number of screen lines to keep above and below the cursor.
set scrolloff=3

" Associate filetypes with extensions
autocmd BufRead,BufNewFile *.json set filetype=jsonc
autocmd BufRead,BufNewFile *.props,*.csproj set filetype=xml

" Yaml files settings
autocmd BufRead,BufNewFile *.yml,*.yaml set tabstop=2 | set shiftwidth=2

" Set Shell

if has('win32')
    set shell=\"C:\\Program\ Files\\PowerShell\\7\\pwsh.exe\"\ -NoLogo
    set shellcmdflag=-Command
endif

if has('unix')
    set shell=pwsh\ -NoLogo
    set shellcmdflag=-Command
endif

" Save file keymaps
nmap <c-s> :w<CR>
vmap <c-s> <Esc><c-s>gv
imap <c-s> <Esc><c-s>
nmap <F2> :update<CR>
vmap <F2> <Esc><F2>gv
imap <F2> <c-o><F2>
nmap ZS :w<CR>
nmap ZA :wa<CR>

" Cursor shape
let &t_EI = "\<ESC>[1 q" "NORMAL mode
let &t_SI = "\<ESC>[5 q" "INSERT mode
" There's problems with 'r' in windows
if has('unix')
    let &t_SR = "\<ESC>[3 q" "REPLACE mode
endif

" Play 'q' macro
nnoremap <Space> @q

